
zuul:
  ribbon-isolation-strategy: thread
  routes:
    wechat-server:
      path: /wx/**
      url: http://localhost:61070/wx
      serviceId: wechat-server
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000
  add-host-header: true
  sensitive-headers:

# forwarding error timeout; 驼峰配置
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000