
zuul:
  ribbon-isolation-strategy: thread
  request:
    versions:
      - v1
      - v2
  routes:
    wechat-server:
      path: /wx/**
      serviceId: wechat-server
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000
  add-host-header: true
  sensitive-headers:

# forwarding error timeout; 驼峰配置
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
management:
  security:
    enabled: false