
zuul:
  ribbon-isolation-strategy: thread
  routes:
    wechat-service:
      path: /wx/**
      service-id: wechat-server
      sensitive-headers:
      custom-sensitive-headers: true
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000

# forwarding error timeout; 驼峰配置
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000